### ISSUE TITLE
Video incorrectly labeled and parts missing

### ISSUE THREAD

**Issue by homotopycolimit** [asseth/EthCC-website#19]
This video is either mislabeled or it is the wrong video for the label 
https://www.youtube.com/watch?v=RPXfqXo7C2Y

- It contains several talks and should be split up. 
- The Colony talk at the end is missing the Q&A session entirely and it was quite informative.

**Comment by blockchainunchained** [comment]
Agreed on splitting videos but we can just direct link to the timestamp for now (which is the case for many of the other talks). The Colony talk is available here: https://www.youtube.com/watch?v=RPXfqXo7C2Y

If you have time would you be able to put in a pull request with the corrections and possibly any of the other video links as found here: https://www.reddit.com/r/ethereum/comments/83mz5q/all_videos_from_ethcc_18_in_paris/

**Comment by homotopycolimit** [comment]
Well more importantly than the correct timestamp link is the missing content.

The Colony talk is missing the entire Q&A session.

**Comment by blockchainunchained** [comment]
Ok, could you please fix it?

**Comment by homotopycolimit** [comment]
How can I fix it if I don't have the video?

**Comment by homotopycolimit** [comment]
To clarify:
This is what we have: https://youtu.be/RPXfqXo7C2Y?t=3338 for Colony.
But where is the rest?

**Comment by homotopycolimit** [comment]
I think that the missing part is not on Youtube yet. We need access to the recordings from the Camera Crew.

**Comment by blockchainunchained** [comment]
As you already saw some of the videos contained multiple talks, have you checked the [agenda (PDF)](https://ethcc.io/ethcc-agenda.pdf)  to see if it is at the beginning or the end of a video containing more than one talk? You can usually see on the first page of the slideshow what the topic is.

**Comment by blockchainunchained** [comment]
There was another talk missed right at the beginning too (can't remember which now) however there are lots that aren't missing but aren't on the website yet if you should happen to find the time. Hopefully someone from AssEth will be able to track down a recording.

**Comment by blockchainunchained** [comment]
A good trick (which I'm sure you know) to run a webserver in the local directory for testing is:

```
python3 -m http.server
```

**Comment by jdetychey** [comment]
Some videos from the second day are missing due to internet break and are being uploaded at the moment.
The company in charge of the stream is editing the video and expect being done by the end of the month

**Comment by jdetychey** [comment]
@homotopycolimit : Colony talk is now online and edited https://youtu.be/W2iTVumBdAI
@blockchainunchained  : all talks are now edited labeled and uploaded on https://www.youtube.com/channel/UCf7zF8tFOb9T58nBo09BhAw
