### ISSUE TITLE
Video title update request for EthCC YouTube

### ISSUE THREAD

**Issue by dmosites** [asseth/EthCC-website#20]
Hello, we renamed my EthCC talk last-minute, and would like to update the title on the YouTube video as well @ https://www.youtube.com/watch?v=JZjHtoe062I

Please update the title to "Don MOSITES - Building a Global Marketplace"

Thank you! :)

**Comment by vincentlg** [comment]
Hello, done !

**Comment by dmosites** [comment]
Thanks!
