### ISSUE TITLE
Wrong time for ECH Workshop

### ISSUE THREAD

**Issue by timbeiko** [asseth/EthCC-website#209]
Hi all, 

The time listed for the Ethereum Cat Herders workshop is wrong on the `Tracks` view of the agenda. It lists 2:10-2:35, while the workshop was supposed to be 1h. 
<img width="539" alt="Screen Shot 2020-02-26 at 9 41 31 AM" src="https://user-images.githubusercontent.com/9390255/75355257-382ec680-587c-11ea-8a66-d60672bdf763.png">

The `Calendar` view lists what I assume is the correct time (1:35-2:35): 
<img width="960" alt="Screen Shot 2020-02-26 at 9 42 18 AM" src="https://user-images.githubusercontent.com/9390255/75355317-4ed51d80-587c-11ea-933e-7a58c48680ca.png">

Could you please confirm the time and have it accurately reflected in both views? 

Thank you!

**Comment by BettinaBF** [comment]
Done :)
