### ISSUE TITLE
Video missing from first four minutes of a talk

### ISSUE THREAD

**Issue by carver** [asseth/EthCC-website#23]
This talk has audio from the beginning, but the video doesn't start until ~4 minutes in:
https://www.youtube.com/watch?v=woqyl04uAjE

@jdetychey asked me to post about it here. Thanks!

**Comment by jdetychey** [comment]
Still trying to find out where this missing video went.
Worst case we will re-edit it from the full stream.

**Comment by jdetychey** [comment]
We looked into it and it seems like the camera was just off for the 4 first minutes. Sorry it's really a bummer :/

**Comment by carver** [comment]
Aw, too bad. Thanks for looking into it. Good luck with EthCC this year!
