### ISSUE TITLE
EthVC tab update

### ISSUE THREAD

**Issue by ElodieDeM** [asseth/EthCC-website#230]
Hello,

Could you please update the EthVC tab (https://ethcc.io/VC-track.html) with the following edits:

- please add a hyperlink to Kaiko's logo to be automatically directed towards Kaiko's website when clicked: www.kaiko.com ?

![image](https://user-images.githubusercontent.com/75246536/100742947-e2271a80-33db-11eb-926c-3eaa09b6ce1e.png)

- please add a line between the 2 paragraphs "why" and "what"?
![image](https://user-images.githubusercontent.com/75246536/100743063-0a167e00-33dc-11eb-9d2e-5d6251141ebe.png)

- please remove "read more" box (in order to allow for the full article to be displayed at once) and only keep "Interested?"
![image](https://user-images.githubusercontent.com/75246536/100743145-30d4b480-33dc-11eb-8bba-71b905796e9b.png)

- please add a "." after each bullet point in order to uniform among columns "Quality" /"Benefits", and add a line after each bullet point (in order to have more space)?

![image](https://user-images.githubusercontent.com/75246536/100743288-68dbf780-33dc-11eb-8d9e-e7c1b6ea6e90.png)

Let me know if you have any questions.

Thank you!
Elodie

**Comment by jdetychey** [comment]
Hi @ElodieDeM 
Thanks for the issue, I believe this issue should be closed now. Can you confirm this is fixed ?
https://ethcc.io/VC-track.html

**Comment by ElodieDeM** [comment]
Hi @jdetychey,

Thank you for getting back to me. I confirm, it is closed.

Thanks,
Elodie
