### ISSUE TITLE
Change landing page for EthCC 2019

### ISSUE THREAD

**Issue by jdetychey** [asseth/EthCC-website#24]
Request for change landing page:

- Move existing website to a section "EthCC 2018" with a button on the landing page

- Include EthCC title "EthCC 2019 edition, 5th, 6th, 7th March 2019 in Paris"

- Include the youtube teaser from last year https://www.youtube.com/watch?v=n_WhlvF3vbI

**Comment by vincentlg** [comment]
We can change the the **video thumbnail** (with Youtube Asseth account)
https://support.google.com/youtube/answer/72431?hl=en

**Desktop version**
<img width="1567" alt="capture d ecran 2018-11-13 a 19 52 13" src="https://user-images.githubusercontent.com/813911/48435971-eb55d800-e77d-11e8-8835-da12d0e9cc26.png">

**Mobile version**
<img width="397" alt="capture d ecran 2018-11-13 a 19 51 53" src="https://user-images.githubusercontent.com/813911/48435973-eb55d800-e77d-11e8-98ab-1b3a39560dc8.png">

**Comment by jdetychey** [comment]
that looks great @vincentlg

**Comment by kurthalex** [comment]
The thumbnail has been changed with uploaded asseth logo
