### ISSUE TITLE
 Change text / video from 70/30% to 60/40% for video spotlight

### ISSUE THREAD

**Issue by jdetychey** [asseth/EthCC-website#58]
As suggested by @BettinaBF

**Comment by jdetychey** [comment]
What do you think of that @vincentlg  ?

**Comment by vincentlg** [comment]
it's not really great, I'll propose another solution within 24 hours.

![screencapture-ethcc-io-2019-02-04-18_42_26](https://user-images.githubusercontent.com/813911/52226265-c2407180-28ac-11e9-8881-33eac0709dcf.png)
