### ISSUE TITLE
Delete "Learn more" add agenda buttons

### ISSUE THREAD

**Issue by jdetychey** [asseth/EthCC-website#9]
Request for:
- deletion of the "Learn More" buttons
- addition of 3 agenda buttons : 
=> DAY 1 mapped to https://docs.google.com/spreadsheets/d/1T1eCQttSGKmnk_mTLWKU9TFhLqjxgQXXS9juM9_E5N0/edit?usp=sharing
=> DAY 2 mapped to https://docs.google.com/spreadsheets/d/1T1eCQttSGKmnk_mTLWKU9TFhLqjxgQXXS9juM9_E5N0/edit?usp=sharing
=> DAY 3 mapped to https://docs.google.com/spreadsheets/d/1T1eCQttSGKmnk_mTLWKU9TFhLqjxgQXXS9juM9_E5N0/edit?usp=sharing

**Comment by jdetychey** [comment]
it turns out the links dont redirect to the proper tab of the spreadsheet, we will do 3 different sheets later

**Comment by jdetychey** [comment]
Ok, got a dynamic link automaticlly updated to PDF:
Day1: https://docs.google.com/spreadsheets/d/e/2PACX-1vR47H-W7fKsTl0o3VWESx4cwywHL9RhjpA2rYJjKlkmQtte3ORCEI8H1nI_7zHTPoRJ8dpJv75zOE2y/pub?gid=986786694&single=true&output=pdf

Embedded version of the entire spreadsheet:
<iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vR47H-W7fKsTl0o3VWESx4cwywHL9RhjpA2rYJjKlkmQtte3ORCEI8H1nI_7zHTPoRJ8dpJv75zOE2y/pubhtml?widget=true&amp;headers=false"></iframe>

**Comment by jdetychey** [comment]
Embedded of the doc:

<iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vR47H-W7fKsTl0o3VWESx4cwywHL9RhjpA2rYJjKlkmQtte3ORCEI8H1nI_7zHTPoRJ8dpJv75zOE2y/pubhtml?widget=true&amp;headers=false"></iframe>

**Comment by vincentlg** [comment]
demo available [here](vincentlg.github.io), I will merge if it's ok
